# Generated by Django 2.2.3 on 2019-07-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='top_trending',
            name='Game_Preferences',
            field=models.TextField(default='give pref. here'),
        ),
        migrations.AddField(
            model_name='top_trending',
            name='Game_Rating',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='top_trending',
            name='Game_Type',
            field=models.TextField(default='game type'),
        ),
        migrations.AlterField(
            model_name='top_trending',
            name='Game_Name',
            field=models.CharField(max_length=270),
        ),
    ]
