# Generated by Django 2.2.3 on 2019-07-11 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20190710_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action_Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Game_Name', models.CharField(max_length=270)),
                ('Game_Type', models.TextField(default='game type')),
                ('Game_Rating', models.FloatField(default=1)),
                ('Game_Preferences', models.TextField(default='give pref. here')),
            ],
        ),
        migrations.CreateModel(
            name='Adventure_Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Game_Name', models.CharField(max_length=270)),
                ('Game_Type', models.TextField(default='game type')),
                ('Game_Rating', models.FloatField(default=1)),
                ('Game_Preferences', models.TextField(default='give pref. here')),
            ],
        ),
        migrations.CreateModel(
            name='Arcade_Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Game_Name', models.CharField(max_length=270)),
                ('Game_Type', models.TextField(default='game type')),
                ('Game_Rating', models.FloatField(default=1)),
                ('Game_Preferences', models.TextField(default='give pref. here')),
            ],
        ),
        migrations.CreateModel(
            name='Fighting_Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Game_Name', models.CharField(max_length=270)),
                ('Game_Type', models.TextField(default='game type')),
                ('Game_Rating', models.FloatField(default=1)),
                ('Game_Preferences', models.TextField(default='give pref. here')),
            ],
        ),
        migrations.CreateModel(
            name='Horror_Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Game_Name', models.CharField(max_length=270)),
                ('Game_Type', models.TextField(default='game type')),
                ('Game_Rating', models.FloatField(default=1)),
                ('Game_Preferences', models.TextField(default='give pref. here')),
            ],
        ),
        migrations.CreateModel(
            name='Puzzle_Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Game_Name', models.CharField(max_length=270)),
                ('Game_Type', models.TextField(default='game type')),
                ('Game_Rating', models.FloatField(default=1)),
                ('Game_Preferences', models.TextField(default='give pref. here')),
            ],
        ),
        migrations.CreateModel(
            name='Racing_Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Game_Name', models.CharField(max_length=270)),
                ('Game_Type', models.TextField(default='game type')),
                ('Game_Rating', models.FloatField(default=1)),
                ('Game_Preferences', models.TextField(default='give pref. here')),
            ],
        ),
        migrations.CreateModel(
            name='Shooting_Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Game_Name', models.CharField(max_length=270)),
                ('Game_Type', models.TextField(default='game type')),
                ('Game_Rating', models.FloatField(default=1)),
                ('Game_Preferences', models.TextField(default='give pref. here')),
            ],
        ),
        migrations.CreateModel(
            name='Sports_Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Game_Name', models.CharField(max_length=270)),
                ('Game_Type', models.TextField(default='game type')),
                ('Game_Rating', models.FloatField(default=1)),
                ('Game_Preferences', models.TextField(default='give pref. here')),
            ],
        ),
        migrations.CreateModel(
            name='Strategy_Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Game_Name', models.CharField(max_length=270)),
                ('Game_Type', models.TextField(default='game type')),
                ('Game_Rating', models.FloatField(default=1)),
                ('Game_Preferences', models.TextField(default='give pref. here')),
            ],
        ),
        migrations.CreateModel(
            name='Survival_Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Game_Name', models.CharField(max_length=270)),
                ('Game_Type', models.TextField(default='game type')),
                ('Game_Rating', models.FloatField(default=1)),
                ('Game_Preferences', models.TextField(default='give pref. here')),
            ],
        ),
        migrations.CreateModel(
            name='War_Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Game_Name', models.CharField(max_length=270)),
                ('Game_Type', models.TextField(default='game type')),
                ('Game_Rating', models.FloatField(default=1)),
                ('Game_Preferences', models.TextField(default='give pref. here')),
            ],
        ),
    ]
