# Generated by Django 2.2.3 on 2019-07-11 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_action_games_adventure_games_arcade_games_fighting_games_horror_games_puzzle_games_racing_games_shoo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Puzzle_Games',
            new_name='Competitive_Games',
        ),
    ]
