# Generated by Django 2.2.3 on 2019-07-17 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_auto_20190715_1553'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Action_Games',
        ),
        migrations.DeleteModel(
            name='Adventure_Games',
        ),
        migrations.DeleteModel(
            name='Arcade_Games',
        ),
        migrations.DeleteModel(
            name='Competitive_Games',
        ),
        migrations.DeleteModel(
            name='Fighting_Games',
        ),
        migrations.DeleteModel(
            name='Horror_Games',
        ),
        migrations.DeleteModel(
            name='Racing_Games',
        ),
        migrations.DeleteModel(
            name='Shooting_Games',
        ),
        migrations.DeleteModel(
            name='Sports_Games',
        ),
        migrations.DeleteModel(
            name='Strategy_Games',
        ),
        migrations.DeleteModel(
            name='Survival_Games',
        ),
        migrations.DeleteModel(
            name='War_Games',
        ),
    ]
