# Generated by Django 2.2.3 on 2019-07-17 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_auto_20190717_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_rating', models.FloatField(verbose_name='default=1')),
                ('game_preference', models.TextField(verbose_name='default=give pref here')),
                ('gameid', models.IntegerField(verbose_name='default=123')),
            ],
        ),
        migrations.CreateModel(
            name='Random_Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Game_Name', models.CharField(max_length=270)),
                ('Game_Type', models.TextField(default='game type')),
            ],
        ),
        migrations.DeleteModel(
            name='Top_Trending',
        ),
        migrations.AddField(
            model_name='category',
            name='gname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='collection.Random_Games'),
        ),
    ]
