# Generated by Django 2.2.3 on 2019-07-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0007_auto_20190717_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='game_preference',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='game_rating',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='gameid',
            field=models.CharField(default='', max_length=255),
        ),
    ]
