# Generated by Django 2.2.3 on 2019-07-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0008_auto_20190717_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='game_preference',
            field=models.TextField(default='', max_length=255),
        ),
    ]
