# Generated by Django 2.2.3 on 2019-07-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0009_auto_20190717_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='game_preference',
        ),
        migrations.RemoveField(
            model_name='category',
            name='game_rating',
        ),
        migrations.RemoveField(
            model_name='category',
            name='gameid',
        ),
        migrations.AddField(
            model_name='category',
            name='developer',
            field=models.CharField(default='-', max_length=250),
        ),
        migrations.AddField(
            model_name='category',
            name='game_id',
            field=models.CharField(default='game', max_length=250),
        ),
        migrations.AddField(
            model_name='category',
            name='genre',
            field=models.CharField(default='-', max_length=250),
        ),
        migrations.AddField(
            model_name='category',
            name='language',
            field=models.CharField(default='-', max_length=250),
        ),
        migrations.AddField(
            model_name='category',
            name='maximum_requirment',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='category',
            name='minimum_requirment',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='category',
            name='platforms',
            field=models.CharField(default='-', max_length=250),
        ),
        migrations.AddField(
            model_name='category',
            name='publisher',
            field=models.CharField(default='-', max_length=250),
        ),
        migrations.AddField(
            model_name='category',
            name='release_date',
            field=models.CharField(default='-', max_length=250),
        ),
        migrations.AddField(
            model_name='category',
            name='summery',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(default='-', max_length=250),
        ),
    ]
