# Generated by Django 2.2.3 on 2019-07-18 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0010_auto_20190718_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='title',
        ),
    ]
