# Generated by Django 2.2.3 on 2019-07-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0011_remove_category_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='game_img',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
