# Generated by Django 2.2.3 on 2019-07-22 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0012_category_game_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='-', max_length=250)),
                ('minimum_requirment', models.TextField(default='-')),
                ('maximum_requirment', models.TextField(default='-')),
                ('release_date', models.CharField(default='-', max_length=250)),
                ('developer', models.CharField(default='-', max_length=250)),
                ('publisher', models.CharField(default='-', max_length=250)),
                ('platforms', models.CharField(default='-', max_length=250)),
                ('summery', models.TextField(default='-')),
                ('genre', models.CharField(default='-', max_length=250)),
                ('game_id', models.CharField(default='game', max_length=250)),
                ('game_img', models.CharField(default='0', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='developer',
        ),
        migrations.RemoveField(
            model_name='category',
            name='game_id',
        ),
        migrations.RemoveField(
            model_name='category',
            name='game_img',
        ),
        migrations.RemoveField(
            model_name='category',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='category',
            name='gname',
        ),
        migrations.RemoveField(
            model_name='category',
            name='language',
        ),
        migrations.RemoveField(
            model_name='category',
            name='maximum_requirment',
        ),
        migrations.RemoveField(
            model_name='category',
            name='minimum_requirment',
        ),
        migrations.RemoveField(
            model_name='category',
            name='platforms',
        ),
        migrations.RemoveField(
            model_name='category',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='category',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='category',
            name='summery',
        ),
        migrations.AddField(
            model_name='category',
            name='cat',
            field=models.CharField(default='sdas', max_length=270),
        ),
        migrations.DeleteModel(
            name='Random_Games',
        ),
        migrations.AddField(
            model_name='games',
            name='gname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='collection.category'),
        ),
    ]
