# Generated by Django 2.2.3 on 2019-07-22 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0013_auto_20190722_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='gname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='collection.category'),
        ),
    ]
