# Generated by Django 2.2.3 on 2019-07-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0014_auto_20190722_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='games',
            old_name='developer',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='games',
            name='maximum_requirment',
        ),
        migrations.RemoveField(
            model_name='games',
            name='minimum_requirment',
        ),
        migrations.AddField(
            model_name='games',
            name='requirement',
            field=models.CharField(default='-', max_length=250),
        ),
        migrations.AddField(
            model_name='games',
            name='screenshot',
            field=models.CharField(default='-', max_length=500),
        ),
        migrations.AlterField(
            model_name='games',
            name='gname',
            field=models.CharField(default='a', max_length=100),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
