# Generated by Django 2.2.3 on 2019-07-31 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0017_auto_20190722_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='download_link',
            field=models.CharField(default='-', max_length=500),
        ),
        migrations.AlterField(
            model_name='games',
            name='language',
            field=models.CharField(default='English', max_length=250),
        ),
    ]
