# Generated by Django 2.2.4 on 2019-08-11 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0018_auto_20190731_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('subject', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='games',
            name='requirement',
            field=models.TextField(default='-'),
        ),
    ]
