# Generated by Django 2.2.3 on 2019-08-14 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0019_auto_20190811_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='screenshot1',
            field=models.CharField(default='-', max_length=500),
        ),
    ]
