# Generated by Django 2.2.3 on 2019-08-14 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0020_games_screenshot1'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='screenshot2',
            field=models.CharField(default='-', max_length=500),
        ),
        migrations.AddField(
            model_name='games',
            name='screenshot3',
            field=models.CharField(default='-', max_length=500),
        ),
        migrations.AddField(
            model_name='games',
            name='screenshot4',
            field=models.CharField(default='-', max_length=500),
        ),
        migrations.AddField(
            model_name='games',
            name='screenshot5',
            field=models.CharField(default='-', max_length=500),
        ),
    ]
