# Generated by Django 2.2.3 on 2019-08-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0022_auto_20190814_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='Comments',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='Username',
        ),
        migrations.AddField(
            model_name='feedback',
            name='country',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='feedback',
            name='firstname',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='feedback',
            name='lastname',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='feedback',
            name='subject',
            field=models.TextField(default='-'),
        ),
    ]
