# Generated by Django 2.2.3 on 2019-08-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0023_auto_20190814_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(default='-', max_length=300)),
                ('Comments', models.CharField(default='-', max_length=400)),
            ],
        ),
    ]
