# Generated by Django 2.2.3 on 2019-08-22 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0024_feedback2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback2',
        ),
    ]
