# Generated by Django 2.2.6 on 2019-11-18 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0026_auto_20190902_2156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='firstname',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='lastname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='comment',
            new_name='suggetion',
        ),
    ]
