# Generated by Django 2.2.6 on 2019-11-18 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0027_auto_20191118_2128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='suggetion',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='email',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='name',
            new_name='lastname',
        ),
    ]
