# Generated by Django 2.2.6 on 2019-11-23 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0029_auto_20191123_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='email',
            new_name='lastname',
        ),
    ]
